namespace AliceInventory.Controllers.AliceResponseRender
{
    public enum ResponseFormat
    {
        GreetingRequested,
        InvalidCountEntered,
        Declined,
        Added,
        AddedMany,
        AddCanceled,
        Deleted,
        DeleteCanceled,
        Multiplied,
        MultiplyCanceled,
        Divided,
        DivisionCanceled,
        AllExceptDeleted,
        ClearRequested,
        Cleared,
        ListRead,
        ItemRead,
        EmptyListRead,
        EmptyItemRead,
        MailSent,
        ShowMail,
        MailRequest,
        MailAdded,
        MailDeleted,
        MailIsEmpty,
        HelpRequested,
        Error,
        ExitRequested,
        EntryNotFound,
        NotEnoughEntryToDelete
    }
}